name: check and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Render.com
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render.com deploy hook
        run: curl -X POST https://api.render.com/deploy/srv-co5cb5un7f5s7382nlhg?key=OVHlzGwUde4
